spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loveInDC?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: qwer1234

mybatis:
  mapper-locations: classpath:com/loveindc/preference/dao/*.xml
  config-location:
    classpath:/mybatis-config.xml
